//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Symlinker.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Symlinker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 © 2010-2016 Alejandro Mora
        ///Version: {0}
        ///e-mail: mail@alejandro.md
        ///
        ///Thanks to Microsoft for the use of their shortcut arrow :) 的本地化字符串。
        /// </summary>
        internal static string AboutDescription {
            get {
                return ResourceManager.GetString("AboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot find the file needed to create links, the creation stopped 的本地化字符串。
        /// </summary>
        internal static string CmdNotFound {
            get {
                return ResourceManager.GetString("CmdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The link name you are using already exists in the selected directory, would you like to DELETE the file and then create a new link? 的本地化字符串。
        /// </summary>
        internal static string DialogDeleteFile {
            get {
                return ResourceManager.GetString("DialogDeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File already there... 的本地化字符串。
        /// </summary>
        internal static string DialogDeleteFileWarning {
            get {
                return ResourceManager.GetString("DialogDeleteFileWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The link name you are using already exists in the selected directory, would you like to DELETE the folder and then create a new link? 的本地化字符串。
        /// </summary>
        internal static string DialogFolderExists {
            get {
                return ResourceManager.GetString("DialogFolderExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Folder already there... 的本地化字符串。
        /// </summary>
        internal static string DialogFolderExistsDialog {
            get {
                return ResourceManager.GetString("DialogFolderExistsDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 One of the directories/files does not exists, please provide valid directories/files 的本地化字符串。
        /// </summary>
        internal static string FilesOrFolderNotExists {
            get {
                return ResourceManager.GetString("FilesOrFolderNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please fill all the blanks spaces with the indicated info 的本地化字符串。
        /// </summary>
        internal static string FillBlanks {
            get {
                return ResourceManager.GetString("FillBlanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap info {
            get {
                object obj = ResourceManager.GetObject("info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Link creation aborted 的本地化字符串。
        /// </summary>
        internal static string LinkCreationAborted {
            get {
                return ResourceManager.GetString("LinkCreationAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aborted Operation 的本地化字符串。
        /// </summary>
        internal static string LinkCreationAbortedWarning {
            get {
                return ResourceManager.GetString("LinkCreationAbortedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Link successfully created 的本地化字符串。
        /// </summary>
        internal static string LinkSuccessfullyCreated {
            get {
                return ResourceManager.GetString("LinkSuccessfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Destination File 的本地化字符串。
        /// </summary>
        internal static string MainWindow_Switcher_Destination_File {
            get {
                return ResourceManager.GetString("MainWindow_Switcher_Destination_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Destination Folder 的本地化字符串。
        /// </summary>
        internal static string MainWindow_Switcher_Destination_Folder {
            get {
                return ResourceManager.GetString("MainWindow_Switcher_Destination_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Link File 的本地化字符串。
        /// </summary>
        internal static string MainWindow_Switcher_Link_File {
            get {
                return ResourceManager.GetString("MainWindow_Switcher_Link_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Link Folder 的本地化字符串。
        /// </summary>
        internal static string MainWindow_Switcher_Link_Folder {
            get {
                return ResourceManager.GetString("MainWindow_Switcher_Link_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Now give a name to the link: 的本地化字符串。
        /// </summary>
        internal static string MainWindow_Switcher_Now_give_a_name_to_the_link_ {
            get {
                return ResourceManager.GetString("MainWindow_Switcher_Now_give_a_name_to_the_link_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Now give a name to your file: 的本地化字符串。
        /// </summary>
        internal static string MainWindow_Switcher_Now_give_a_name_to_your_file_ {
            get {
                return ResourceManager.GetString("MainWindow_Switcher_Now_give_a_name_to_your_file_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select the path to the real file you want to link: 的本地化字符串。
        /// </summary>
        internal static string MainWindow_Switcher_Please_select_the_path_to_the_real_file_you_want_to_link_ {
            get {
                return ResourceManager.GetString("MainWindow_Switcher_Please_select_the_path_to_the_real_file_you_want_to_link_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select the path to the real folder you want to link: 的本地化字符串。
        /// </summary>
        internal static string MainWindow_Switcher_Please_select_the_path_to_the_real_folder_you_want_to_link_ {
            get {
                return ResourceManager.GetString("MainWindow_Switcher_Please_select_the_path_to_the_real_folder_you_want_to_link_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        internal static string MessageBoxAboutTitle {
            get {
                return ResourceManager.GetString("MessageBoxAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        internal static string MessageBoxErrorTitle {
            get {
                return ResourceManager.GetString("MessageBoxErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error has ocurred: 的本地化字符串。
        /// </summary>
        internal static string MessageBoxExceptionOcurred {
            get {
                return ResourceManager.GetString("MessageBoxExceptionOcurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success 的本地化字符串。
        /// </summary>
        internal static string MessageBoxSuccessTitle {
            get {
                return ResourceManager.GetString("MessageBoxSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 With this option you can choose between creating file symbolic links; \nthis is using a file to point to another file, or folder symbolic links; this \nis using folders that point to other folders 的本地化字符串。
        /// </summary>
        internal static string TooltipTypeSelectorDescription {
            get {
                return ResourceManager.GetString("TooltipTypeSelectorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Symbolic Link type selector 的本地化字符串。
        /// </summary>
        internal static string TooltipTypeSelectorTitle {
            get {
                return ResourceManager.GetString("TooltipTypeSelectorTitle", resourceCulture);
            }
        }
    }
}
